export const ADD_CART = 'ADD_CART';
export const CHANGE_MESSAGE = 'CHANGE_MASSAGE';
export const DELETE_PRODUCT_IN_CART = 'DELETE_PRODUCT_IN_CART';
export const UPDATE_PRODUCT_IN_CART = 'UPDATE_PRODUCT_IN_CART';


