export const MEG_ADD_TO_CART_SUCCESS = 'Successful purchase'
export const MEG_UPDATE_CART_SUCCESS = 'Update cart successfully'
export const MEG_DELETE_CART_SUCCESS = 'Successfully deleted the product'
export const MEG_CART_EMPTY = 'You have not items in your shoping cart'
export const MEG_WELLCOME = 'Wellcome to my shop'
export const MEG_EMTY_INVENTORY = 'Sorry! We have no more inventory'